function createfigure(XMatrix1, YMatrix1, ZMatrix1, XMatrix2, YMatrix2, ZMatrix2)
%CREATEFIGURE(XMatrix1, YMatrix1, ZMatrix1, XMatrix2, YMatrix2, ZMatrix2)
%  XMATRIX1:  matrix of plot3 x data
%  YMATRIX1:  matrix of plot3 y data
%  ZMATRIX1:  matrix of plot3 z data
%  XMATRIX2:  matrix of plot3 x data
%  YMATRIX2:  matrix of plot3 y data
%  ZMATRIX2:  matrix of plot3 z data

%  Auto-generated by MATLAB on 30-May-2023 12:23:15

% Create figure
figure('OuterPosition',[672 450 576 513]);

% Create axes
axes1 = axes;
hold(axes1,'on');

% Create multiple line objects using matrix input to plot3
plot31 = plot3(XMatrix1,YMatrix1,ZMatrix1);
set(plot31(1),'Color',[1 0 0]);
set(plot31(2),'Color',[0 0 1]);

% Create multiple line objects using matrix input to plot3
plot32 = plot3(XMatrix2,YMatrix2,ZMatrix2,'Marker','o','LineStyle','none');
set(plot32(1),'MarkerFaceColor',[1 0 0]);
set(plot32(2),'MarkerFaceColor',[0 0 0]);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[671412.936236779 678141.3125]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[5704239.5508245 5705065.99710548]);
% Uncomment the following line to preserve the Z-limits of the axes
% zlim(axes1,[0 661.157024793388]);
view(axes1,[133.221092648286 2.4208405995525]);
grid(axes1,'on');
hold(axes1,'off');
